apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: quiz
type: Opaque
data:
  mongo-uri: const uri = "mongodb+srv://AdminUser:malik0786@mongocluster.u92cud5.mongodb.net/Cruds?retryWrites=true&w=majority&appName=MongoCluster";
